title:              Data Artist
email:              jwsohn612@gmail.com
description:        to disclose behind story of data 
author:             Jinwon Sohn
baseurl:            "/"
url:                "https://jwsohn612.github.io"

# Social Profiles
# twitter_username:   
github_username:    jwsohn612
#facebook_username:  Jinwon Sohn
#instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
